<?php include 'view/includes/header.phtml'; ?>


<main>
    <div class="detalle-curso">
        <div class="detalle-imagen">
            <img src="<?php echo BASE_URL; ?>view/imgs/<?php echo ($curso->imagen)?>" alt="Imagen de <?php echo($curso->titulo) ?>">
        </div>
        <div class="detalle-info">
            <h1 class= "detalle-titulo"><?php echo($curso->titulo)?></h1>
            <p class="detalle-descripcion"><?php echo($curso->descripcion)?></p>
            <p class="detalle-instructor"><?php echo($curso->instructor)?></p>
        </div>
    </div>

</main>



<?php include 'view/includes/footer.phtml'; ?>