<?php include 'view/includes/header.phtml'; ?>

<main class="main-content">
    <section class="category-list-section">
        <div class="category-header">
            <h1 class="section-title">Explora Nuestras Secciones de Cursos</h1>
            <p class="section-subtitle">Encuentra el camino hacia el conocimiento que buscas en nuestra biblioteca de temas.</p>
        </div>

        <div class="category-grid">
            
            <?php if (isset($categorias) && is_array($categorias)): ?>
                <?php foreach ($categorias as $cat): ?>
                    <div class="category-card">
                    <a href="<?php echo BASE_URL; ?>listarPorCategoria/<?php echo ($cat->id); ?>" class="category-card">
                        
                        <div class="card-icon">
                            <i class="fas fa-code"></i> 
                        </div>

                        <h2 class="card-title">
                            <?php echo($cat->nombre); ?>
                        </h2>
                        
                        <span class="card-count">
                            Comenzar a Explorar →
                        </span>
                    </a>
                        <div class="card-actions">
                            <?php if (!empty($_SESSION['ES_ADMIN'])): ?>                
                            <div class="admin-actions">
                                <a href="editarCat/<?php echo $cat->id ?>" class="btn-admin-edit">Editar</a>
                                <a href="eliminarCat/<?php echo $cat->id ?>" class="btn-admin-delete">Borrar</a>
                            </div>
                            <?php endif ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>

        </div>
    </section>
</main>

<?php include 'view/includes/footer.phtml'; ?>